SESSION_TOKEN_LENGTH = 32

DEFAULT_INITIAL_TOKENS = 2
DEFAULT_TIMELINE_LENGTH = 10
DEFAULT_GUESS_TIMEOUT = 30000

TOKEN_COST_POSITION_GUESS = 1
TOKEN_COST_YEAR_GUESS = 1
TOKEN_COST_EXCHANGE_TRACK = 1
TOKEN_COST_BUY_TRACK = 3

TOKEN_GAIN_YEAR_GUESS = 1
