name: Frontend

on:
  push:
    paths:
      - ".github/**"
      - "frontend/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build image
        uses: docker/build-push-action@v4
        with:
          context: "{{defaultContext}}:frontend"
          cache-from: type=gha
          cache-to: type=gha,mode=max

  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend
    steps:
      - uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 19.2.0

      - name: Cache dependencies
        id: cache-dependencies
        uses: actions/cache@v3
        with:
          path: frontend/node_modules
          key: node-deps-${{ hashFiles('frontend/package-lock.json') }}

      - name: Install dependencies
        run: npm ci
        if: steps.cache-dependencies.outputs.cache-hit != 'true'

      - name: Run eslint
        run: npm run lint

      - name: Check translations
        run: npm run i18n:extract && npm run i18n:check

  deploy:
    runs-on: ubuntu-latest
    needs:
      - build
      - test
    if: github.ref == 'refs/heads/main'
    defaults:
      run:
        working-directory: ./frontend
    steps:
      - uses: actions/checkout@v3

      - uses: superfly/flyctl-actions/setup-flyctl@master

      - run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN_FRONTEND }}
